swagger: '2.0'
info:
  title: swaggertest
  description: swaggertest
  version: "0.0.1"
host: localhost:8000
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  '/search':
    get:
      summary: get user information
      tags:
        - user
      parameters:
        - name: user_id
          type: integer
          in: query
          format: int32
          required: true
          description: user id
      responses:
        '200':
          description: OK
          schema:  
            $ref: '#/definitions/User'
        default:
          description: error
          schema:
            $ref: '#/definitions/Error'
definitions:
  User:
    type: object
    required:
      - user_id
    properties:
      user_id:
        type: integer
        format: int32
        description: user id
      name:
        type: string
        description: name
  Error:
    type: object
    properties:
      message:
        type: string
